apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-data
  namespace: hass
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2000-01.com.synology:DiskStation.hass.cfbdb2acd5
    targetPortal: 10.0.2.4
    lun: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-data
  namespace: hass
spec:
  volumeName: hass-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi